### ISSUE TITLE
beeswarm-0.2.1: "corral" methods not working

### ISSUE THREAD

**Issue by ivso** [aroneklund/beeswarm#1]
The example code from the `beeswarm()` help page [1] as well as the one from the [project webpage](http://www.cbs.dtu.dk/~eklund/beeswarm/) [2] produces plots with the default, i.e. `corral = none`.

    # [1]
    ## Generate some random data
    set.seed(123)
    distro <- list(runif = runif(100, min = -3, max = 3), 
                   rnorm = rnorm(100))
    ## Compare the five "corral" methods 
    for (ii in c("none", "gutter", "wrap", "random", "omit"))
      {
      beeswarm(distro, 
               pch = 21, col = 2:4, bg = "#00000050",
               corral = ii, 
               main = paste('corral = "', ii, '"', sep = ''))
    }

    # [2]
    distributions <- list(runif = runif(100, min = -3, max = 3), 
                          rnorm = rnorm(100),
                          rlnorm = rlnorm(100, sdlog = 0.5))
    ## Demonstrate the 'corral' methods
    par(mfrow = c(2,3))
    beeswarm(distributions, col = 2:4, 
             main = 'corral = "none" (default)')
    beeswarm(distributions, col = 2:4, corral = "gutter", 
             main = 'corral = "gutter"')
    beeswarm(distributions, col = 2:4, corral = "wrap", 
             main = 'corral = "wrap"')
    beeswarm(distributions, col = 2:4, corral = "random", 
             main = 'corral = "random"')
    beeswarm(distributions, col = 2:4, corral = "omit", 
             main = 'corral = "omit"')

#### Session Info
    devtools::session_info()
    Session info -----------------------------------------------------------------------------------------------------------
    setting  value                       
    version  R version 3.2.3 (2015-12-10)
    system   x86_64, linux-gnu           
    ui       RStudio (0.99.491)          
    language en_US:en                    
    collate  en_US.UTF-8                 
    tz       <NA>                        
    date     2016-02-04                  
   
    Packages ---------------------------------------------------------------------------------------------------------------
    package  * version date       source        
    beeswarm * 0.2.1   2015-08-29 CRAN (R 3.2.3)
    devtools   1.10.0  2016-01-23 CRAN (R 3.2.3)
    digest     0.6.9   2016-01-08 CRAN (R 3.2.3)
    memoise    1.0.0   2016-01-29 CRAN (R 3.2.3)

**Comment by aroneklund** [comment]
Hi,

If the plotting area is large enough to contain all the points, then none of the "corral" methods will have an effect.  Could this explain your observations? Otherwise it would be helpful to see your graphical output.

**Comment by ivso** [comment]
Thanks for the clarification and for providing the wonderful `beeswarm` package!!! Below I have included the plot that led me to believe that there should be a problem with the `corral = ...` methods:
![rplot](https://cloud.githubusercontent.com/assets/1001369/12851117/d38746a2-cc30-11e5-9744-319394bbd1e4.png)
The plotting area for each group is (obviously) sufficiently large to contain all the points, so nothing happens... To avoid further confusion I think it would be helpful if you could put a note into the documentation to highlight this behavior, and also, perhaps, to modify the code-examples to force the desired outcome. I have doubled the samples for `runif`, `rnorm`, and `rlnorm` to `200` and now the plot shows the `corral` effect (on a ca. 1000px wide plotting window):
![rplot02](https://cloud.githubusercontent.com/assets/1001369/12852062/d9d8399e-cc35-11e5-9fe2-63d0f8e60628.png)

**Comment by aroneklund** [comment]
Thanks for the feedback! I modified the example to use 200 points, as you suggested.
