### ISSUE TITLE
Discussion/feature request: allow passing additional points to avoid

### ISSUE THREAD

**Issue by bersbersbers** [aroneklund/beeswarm#12]
With the following code, it can happen that the swarm overlaps with the mean value:

```R
        ...
        stat_summary(
            fun = "mean",
            geom = "point",
            shape = 23,
        ) +
        ggbeeswarm::geom_beeswarm() +
        ...
```

Is there a way to pass pre-existing points that `beeswarm` would consider in the jittering (without plotting them)?

**Comment by aroneklund** [comment]
I'm not sure I understand the question, and I wonder if this is more of a ggbeeswarm question than a beeswarm question.  Beeswarm returns the plot data invisibly as a data frame; would this help somehow?

**Comment by bersbersbers** [comment]
Well, the interace is `ggbeeswarm`, yes, but it won't be able to solve this itself I'd say. Consider this example:

```R
df <- data.frame(x = "A", y = rnorm(100))
ggplot2::ggplot(df, ggplot2::aes(x = x, y = y)) + 
    ggbeeswarm::geom_beeswarm() + 
    ggplot2::stat_summary(
        fun = "mean",
        geom = "point",
        color = "red",
    )
```

The mean is overlapping some black points:

![image](https://user-images.githubusercontent.com/12128514/117319632-c98bc680-ae8b-11eb-9846-f12917a753ce.png)

A good solution I could think of is to add an interface for "phantom points" that will be put in their position, but not output. So a call to `beeswarm(points, phantom_points)` would give you a swarm of `points` with holes at `phantom_points`.

**Comment by jtrim-ons** [comment]
@bersbersbers It's not what you asked for, but would a horizontal line instead of a circle to show the mean be good enough? That seems like a more conventional approach. It would also be my preference from a visualisation point of view, as it clearly distinguishes between the data points and a summary.

**Comment by bersbersbers** [comment]
@jtrim-ons I must admit that is a strong argument. I currently combine `geom_violin` (with a line indicating the violin's median via `draw_quantiles`) with `geom_beeswarm`, and so I thought indicating the mean by a point would be good idea to distinguish median from mean. But I agree that I may need to distinguish the mean from the points better - especially so since the mean is almost never one of the points. I need to try this out!

Thanks for that input, it's good that I marked this as "Discussion" as well.

**Comment by aroneklund** [comment]
I agree; indicating the mean with a point that (aside from color) looks like a data point seems like it could be misleading. But if you want to do this anyway, maybe it would be possible to append the mean value to your original data, and then color it red?

**Comment by bersbersbers** [comment]
> But if you want to do this anyway, maybe it would be possible to append the mean value to your original data, and then color it red?

Yes, that's possible - although I would find it odd if the mean value was not centered, and I guess that is hard to control as well.

Anyway, you both convinced me the whole approach makes little sense, so I am closing this issue. Thanks for the discussion!
