### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mmahmoudian** [aroneklund/beeswarm#16]
The link in the README (http://www.cbs.dtu.dk/~eklund/beeswarm/) is broken. It would be nice and customary to have the examples in a vignette instead of a separate website. As far as i can remember there was a vignette but it seems it is missing from the latest CRAN submission: https://cran.r-project.org/web/packages/beeswarm/index.html

**Comment by aroneklund** [comment]
Thanks for pointing out the broken link. I have removed it.

There has never been a vignette, unfortunately. I agree that it would be nice!  Perhaps a project for a rainy day...
