### ISSUE TITLE
beeswarm-0.2.1: "corral" and "side"

### ISSUE THREAD

**Issue by schmockolaus** [aroneklund/beeswarm#2]
I think there is a minor issue with beeswarm. "corral = random" and "corral = wrap" do not work properly when using "side". The points spill over to the other side.

For instance, if you modify the example code by adding "side=1": 

```
distributions <- list(runif = runif(200, min = -3, max = 3), rnorm = rnorm(200), rlnorm = rlnorm(200, sdlog = 0.5))
par(mfrow = c(2,3))
beeswarm(distributions, col = 2:4, side=1, main = 'corral = "none" (default)')
beeswarm(distributions, col = 2:4, side=1, corral = "gutter", main = 'corral = "gutter"')
beeswarm(distributions, col = 2:4, side=1, corral = "wrap", main = 'corral = "wrap"')
beeswarm(distributions, col = 2:4, side=1, corral = "random", main = 'corral = "random"')
beeswarm(distributions, col = 2:4, side=1, corral = "omit", main = 'corral = "omit"')
```

This is what is being plotted:

![corral and side](https://cloud.githubusercontent.com/assets/4981344/14713000/b99308d6-07df-11e6-818d-db55fc8d4090.png)

It would be nice if you could fix that or give me a hint how to circumvent this issue.

Thanks a lot!

**Comment by aroneklund** [comment]
Thanks for pointing this out.  I think I managed to solve the problem in version 0.2.3, available now on GitHub and hopefully soon on CRAN.
