### ISSUE TITLE
Pass vector of point sizes to cex?

### ISSUE THREAD

**Issue by alexpreynolds** [aroneklund/beeswarm#3]
When rendering a large number of points, reducing the `cex` parameter will shrink the points and make a plot more legible. 

However, when using coloring to highlight a small subset of points, that coloring loses its impact because the points are smaller and more difficult to read.

As a feature request, it would be useful to be able to pass `cex` (or a similar argument) a vector of sizes that correspond to the desired point size. Then specific points of interest can be highlighted both by color and relative size.

**Comment by aroneklund** [comment]
Thanks. I think this is a good idea, and it should be relatively painless to implement.

**Comment by aroneklund** [comment]
OK, done!  Here is an example:

    beeswarm(mpg ~ cyl, data = mtcars, cex = 3, 
    pwcol = gear, pwbg = am + 1, pwpch = gear + 18, pwcex = hp / 335)

**Comment by aroneklund** [comment]
Just to be clear: the new argument is `pwcex`, and it adjusts the size of the individual points, relative to the argument `cex` and `par("cex")`.  

However, `pwcex` doesn't affect the point layout.

**Comment by alexpreynolds** [comment]
Thanks very much!
