### ISSUE TITLE
Option to include NA as a factor level when plotting

### ISSUE THREAD

**Issue by ndsubison2178** [aroneklund/beeswarm#7]
My Y variable is continuous
My x variable has 3 levels (Yes, Maybe, No)

I am using 
beeswarm( y ~ x, data=mydataset, log=TRUE)
This creates a plot with 3 groups and dots corresponding to the y in each group, this is fine.

I have some NA values in my X variable. I want to include that  as well.
I am interested in visualizing 4 groups (Yes, Maybe, No, NA) instead of just 3 groups (Yes, Maybe, No).

Is there an option in beeswarm to include NA in x axis as a factor level ?

**Comment by aroneklund** [comment]
Hi. Beeswarm is intended to work more or less the same as `boxplot` and `stripchart`, both of which ignore NAs in the grouping variable. So I probably can't be convinced to change this behavior.  Maybe you could re-code your X variable to include "NA" as one of the levels in the factor?

**Comment by ndsubison2178** [comment]
Thanks Aron, no issues.
