### ISSUE TITLE
groups with identical data values

### ISSUE THREAD

**Issue by raredd** [aroneklund/beeswarm#8]
When I have a group with the same y-values, every arranging method except the default gives me all missing values.

`'swarm'` is the only method that acts as I would expect:

```r
(beeswarm::beeswarm(c(1, 1), method = 'swarm'))
#          x y pch   col bg x.orig y.orig
# 1 1.000000 1   1 black NA     NA      1
# 2 1.008484 1   1 black NA     NA      1

(beeswarm::beeswarm(c(1, 1), method = 'center'))
#    x  y pch   col bg x.orig y.orig
# 1 NA NA   1 black NA     NA      1
# 2 NA NA   1 black NA     NA      1

(beeswarm::beeswarm(rep(1, 10), method = 'center'))
#     x  y pch   col bg x.orig y.orig
# 1  NA NA   1 black NA     NA      1
# 2  NA NA   1 black NA     NA      1
# 3  NA NA   1 black NA     NA      1
# 4  NA NA   1 black NA     NA      1
# ...
```

However, if at least one of the points is different, I get the expected result:

```r
(beeswarm::beeswarm(c(rep(1, 10), 2), method = 'square'))
#            x        y pch   col bg x.orig y.orig
# 1  0.9660631 1.001685   1 black NA     NA      1
# 2  0.9745473 1.001685   1 black NA     NA      1
# 3  0.9830316 1.001685   1 black NA     NA      1
# 4  0.9915158 1.001685   1 black NA     NA      1
# ...
```

**Comment by raredd** [comment]
I added `include.lowest = TRUE` to the `cut`s [here](https://github.com/aroneklund/beeswarm/blob/master/R/beeswarm.R#L213) and [here](https://github.com/aroneklund/beeswarm/blob/master/R/beeswarm.R#L224), and it seems to be fixed. I don't know if this will break the desired binning in other situations, however.

**Comment by aroneklund** [comment]
Thanks for pointing out the bug, and for suggesting a fix!  I don't think `include.lowest = TRUE` would will break anything. I'll push the change very soon.
