### ISSUE TITLE
A suggestion for a compact layout algorithm

### ISSUE THREAD

**Issue by jtrim-ons** [aroneklund/beeswarm#9]
Thanks for the great package.

I recently had an idea for an alternative beeswarm algorithm, and I thought I'd share it here in case it's something that might be useful to include in the beeswarm package. Equally, my approach might be a terrible idea for some reason and I'd love to receive feedback if so! :-) Also copying in @eclarke, @sherrillmix and @csdaw because of your work on ggbeeswarm{,2}.

The idea is that we don't decide in advance the order in which points will be placed. Rather, the algorithm decides on each iteration which single point to place next. It does this by choosing a point that can be placed as close as possible to the non-data axis without overlapping any point that has been placed so far. Ties are broken by `priority` (e.g. `"ascending"`).

The following two examples use `priority="ascending"`. The first uses the new `"compactswarm"` method; the second uses the existing `"swarm"` method.

![image](https://user-images.githubusercontent.com/79704945/113624753-f0ba6280-9657-11eb-8bd0-292bde768763.png)

![image](https://user-images.githubusercontent.com/79704945/113624820-0596f600-9658-11eb-98cc-c3b0f9aae190.png)

The following two examples use `priority="random"`. Again, it is the new method followed by the existing one.

![image](https://user-images.githubusercontent.com/79704945/113624864-1182b800-9658-11eb-8ee4-1526d053e5b9.png)

![image](https://user-images.githubusercontent.com/79704945/113624890-1cd5e380-9658-11eb-96d3-e93ec85d336a.png)

To my eye, the new method often creates a tidier-looking plot, and it tends to require less horizontal space (if the data axis is vertical). A downside is that my current R implementation at https://github.com/jtrim-ons/beeswarm is slower than the `"swarm"` method (perhaps ~5 times slower if there are 2000 data points).

I also have a faster JS implementation at https://github.com/jtrim-ons/accurate-beeswarm-plot.

I'd be happy to open a PR if any of this is helpful.

**Comment by aroneklund** [comment]
Thanks! This definitely seems like an improvement to me. 

I'd like to play with it a bit before merging your version -- hopefully I can find some time in the next day or so...

**Comment by jtrim-ons** [comment]
@aroneklund Thanks for the quick reply! It's really nice to hear that your initial reaction is positive.

Of course, take as long as you need to review it. I'm afraid I haven't a lot of R experience, so my code is likely to be unidiomatic or inefficient in places.

**Comment by jtrim-ons** [comment]
Something that I haven't checked yet is NA x values. I guess they'll cause problems with my implementation.

**Comment by aroneklund** [comment]
Sorry for my slow response. I think it looks great! Could you submit a pull request?

**Comment by jtrim-ons** [comment]
I'm glad you like it! I've submitted PR #10.

**Comment by aroneklund** [comment]
Thanks, I think this is a huge improvement! (at least for n < a few thousand)

If this were a new package, I would make compactswarm the default.
